Update linting tools (#155)
* Bump isort(5.10.0) and mypy(0.960) to latest

* Add missing variable annotation in migration

Fixes: redun/backends/db/alembic/versions/30ffbaee18cd_add_task_version_and_backfill_companion_values.py:59: error: Need type annotation for 'redun_task'  [var-annotated]

* Check for string before calling strip()

Fixes: redun/scheduler.py:462: error: Item 'None' of 'Optional[str]' has no attribute 'strip'  [union-attr]

* Add missing types package for python-dateutil

Fixes errors of the form: Library stubs not installed for dateutil

* Use collections.abc in bcoding, available since py3.3

* Remove TODO, self.line is a property not a typo for self._line

* Remove TODO: keep defaults consistent with FrameSummary base

* Remove TODO for typing dependencies