Fix nested value iteration for dataclasses instantiated from user-defined generics (#222)
This PR makes nested value iteration support for dataclasses a little more robust,
and fixes a corner case related to handling dataclass objects that are instantiated
from user-defined generics.

The existing implementation for dataclasses uses objects' `__dict__` field to iterate
through/map over its attributes.  Using `__dict__` is problematic for dataclasses,
because it might contain keys other than the class' defined fields, as is the case here:

```python
T = TypeVar("T")

@dataclass
class Foo(Generic[T]):
    bar: T

test_foo = Foo[int](1)

print(test_foo.__dict__)
> {'bar': 1, '__orig_class__': __main__.Foo[int]}
```

This means that `map_nested_value` breaks
```python
map_nested_value(<func>, test_foo)
> TypeError: __init__() got an unexpected keyword argument '__orig_class__'
```
as we cannot reconstruct an instance of `Foo[int]` after mapping through
its nested values.

To handle this, we use [dataclasses.fields](https://docs.python.org/3/library/dataclasses.html?highlight=field#dataclasses.fields) to explicitly iterate/map through
only defined fields, instead of whatever is in the instance `__dict__`.